name: Check tox tests

on:
  push:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  check_document:
    name: Check packaging 📦
    runs-on: ubuntu-22.04
    env:
      AQT_TEST_EMAIL: ${{ secrets.AQT_TEST_EMAIL }}
      AQT_TEST_PASSWORD: ${{ secrets.AQT_TEST_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 20
        fetch-tags: true
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install tools
      run: |
        pip install -U pip
        pip install tox tox-gh-actions coveralls coverage[toml]
    - name: Test
      run: |
        tox
        coverage xml -o cobertura.xml
      env:
        PYTEST_ADDOPTS: --cov-config=pyproject.toml --cov --cov-append --verbose
